@url = http://localhost:5000/solution-to-problem
#@url = https://the80by20.azurewebsites.net/solution-to-problem

@accessToken = 

###
GET {{url}}

###
POST {{url}}/problems
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "",
  "category": "00000000-0000-0000-0000-000000000003",
  "solutionElementTypes": [
    0
  ]
}

###
POST {{url}}/problems
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "description",
  "category": "00000000-0000-0000-0000-000000000003",
  "solutionElementTypes": [
    0
  ]
}

###
GET {{url}}/problems
Authorization: Bearer {{accessToken}}