@url = http://localhost:5000/sale
#@url = https://the80by20.azurewebsites.net/solution-to-problem

@solutionId = f87f77ac-10c1-4d58-9f81-d7a73b1df363

@accessToken = 

###
GET {{url}}/home



###
POST {{url}}/products/CreateProductMocked/{{solutionId}}
Authorization: Bearer {{accessToken}}